BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Bookings CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Vehicles_Slots CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Students CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE Students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    total_co2_saved_kg NUMBER(12, 3) DEFAULT 0 NOT NULL
);

CREATE TABLE Vehicles_Slots (
    slot_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type VARCHAR2(100) NOT NULL,
    route VARCHAR2(255) NOT NULL,
    slot_time TIMESTAMP NOT NULL,
    capacity NUMBER(10) NOT NULL,
    booked_count NUMBER(10) DEFAULT 0 NOT NULL,
    distance_km NUMBER(10, 2) NOT NULL,
    emission_factor NUMBER(10, 4) NOT NULL,
    CONSTRAINT vehicles_slots_capacity_ck CHECK (capacity > 0),
    CONSTRAINT vehicles_slots_booked_ck CHECK (booked_count >= 0 AND booked_count <= capacity)
);

CREATE TABLE Bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    slot_id NUMBER NOT NULL,
    booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT bookings_student_fk FOREIGN KEY (student_id) REFERENCES Students(student_id),
    CONSTRAINT bookings_slot_fk FOREIGN KEY (slot_id) REFERENCES Vehicles_Slots(slot_id)
);

INSERT INTO Students (student_id, name, email, password)
VALUES (1, 'Demo Student', 'test@campus.edu', 'test123');

INSERT INTO Vehicles_Slots
    (slot_id, vehicle_type, route, slot_time, capacity, booked_count, distance_km, emission_factor)
VALUES
    (1, 'Electric Shuttle', 'North Campus - Main Gate',
     TO_TIMESTAMP('2026-09-08 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), 20, 0, 8.5, 0.0200);

INSERT INTO Vehicles_Slots
    (slot_id, vehicle_type, route, slot_time, capacity, booked_count, distance_km, emission_factor)
VALUES
    (2, 'Campus Bus', 'Residence Hall - Library',
     TO_TIMESTAMP('2026-09-08 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 35, 0, 5.2, 0.0890);

INSERT INTO Vehicles_Slots
    (slot_id, vehicle_type, route, slot_time, capacity, booked_count, distance_km, emission_factor)
VALUES
    (3, 'Shared Van', 'Science Block - Innovation Hub',
     TO_TIMESTAMP('2026-09-08 10:15:00', 'YYYY-MM-DD HH24:MI:SS'), 8, 0, 3.7, 0.1200);

COMMIT;
